server:
  port: 9010
spring:
  # Quartz 的配置，对应 QuartzProperties 配置类
  quartz:
    job-store-type: memory # Job 存储器类型。默认为 memory 表示内存，可选 jdbc 使用数据库。
    auto-startup: true # Quartz 是否自动启动
    startup-delay: 0 # 延迟 N 秒启动
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    overwrite-existing-jobs: false # 是否覆盖已有 Job 的配置
    properties: # 添加 Quartz Scheduler 附加属性
      org:
        quartz:
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
  #    jdbc: # 这里暂时不说明，使用 JDBC 的 JobStore 的时候，才需要配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///1-learn-system?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 2048711712P!
      initial-size: 10
      max-active: 60
      min-idle: 5
      filters: mergeStat,log4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
        log4j:
          enabled: true
      stat-view-servlet:
        login-username: root
        login-password: 2048711712P!
        enabled: true
        allow:
        deny:
      test-while-idle: true
      test-on-borrow: true
      remove-abandoned: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      socket-timeout: 300000
      connect-timeout: 300000